In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../../results/v3/gender/predictions/CNKI_uniqueChineseAllGivenNames_gender.csv')
df.shape

(46144, 43)

In [3]:
df_gt = df.query("gt == True")
df_gt.shape

(166, 43)

In [4]:
df_gt.columns

Index(['givenname', 'ngender_r', 'gender_w', 'a1', 'a2', 'a3', 'a4', 'a5',
       'a6', 'a7', 'a8', 'a9', 'a10', 'a11', 'single_char', 'round', 'gt',
       'gender_n', 'ngender_n', 'score_n', 'prob_n', 'ngender_w', 'mean',
       'mean_ngender_rnw', 'mean_ngender_rn', 'mean_ngender_rw',
       'mean_ngender_nw', 'median', 'median_ngender_rnw', 'median_ngender_rn',
       'median_ngender_rw', 'median_ngender_nw', 'std', 'std_ngender_rnw',
       'std_ngender_rn', 'std_ngender_rw', 'std_ngender_nw', 'mode',
       'mode_ngender_rnw', 'mode_ngender_rn', 'mode_ngender_rw',
       'mode_ngender_nw', 'gender_nw'],
      dtype='object')

In [5]:
tmp = df_gt.query("single_char == True and gender_nw == 'unknown'")[['givenname','ngender_r','gender_w','gender_n','gender_nw','a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'a10', 'a11','mean','median','mode','round']]
tmp.reset_index(drop=True)

,givenname,ngender_r,gender_w,gender_n,gender_nw,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,mean,median,mode,round
0,𬒗,NaN,unknown,unknown,unknown,2.0,2.0,1.0,1.0,3.0,3.0,3.0,2.0,3.0,3.0,2.0,0.312500,0.250,0.25,2.0
1,𬕂,NaN,unknown,unknown,unknown,2.0,2.0,2.0,2.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,0.375000,0.375,0.25,2.0
2,𬘬,NaN,unknown,unknown,unknown,3.0,5.0,4.0,5.0,4.0,3.0,4.0,5.0,4.0,4.0,5.0,0.750000,0.750,0.75,2.0
3,𬘭,NaN,unknown,unknown,unknown,4.0,5.0,5.0,5.0,3.0,5.0,4.0,4.0,5.0,5.0,5.0,0.833333,1.000,1.00,2.0
4,𬬹,NaN,unknown,unknown,unknown,2.0,1.0,2.0,2.0,3.0,2.0,3.0,1.0,2.0,2.0,2.0,0.250000,0.250,0.25,2.0
5,𬬻,NaN,unknown,unknown,unknown,3.0,2.0,2.0,3.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,0.250000,0.250,0.25,2.0
6,𬭬,NaN,unknown,unknown,unknown,4.0,4.0,2.0,1.0,4.0,2.0,4.0,4.0,3.0,3.0,2.0,0.479167,0.500,0.75,2.0
7,𬯎,NaN,unknown,unknown,unknown,3.0,2.0,2.0,2.0,3.0,4.0,3.0,2.0,2.0,3.0,2.0,0.375000,0.250,0.25,2.0
8,𬳵,NaN,unknown,unknown,unknown,3.0,1.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,3.0,3.0,0.333333,0.250,0.25,2.0
9,𬺓,NaN,unknown,unknown,unknown,3.0,2.0,1.0,4.0,3.0,2.0,3.0,3.0,3.0,2.0,3.0,0.395833,0.500,0.50,2.0

In [6]:
tmp['mean'].mean()

0.4354166666666666

In [7]:
tmp.query('givenname=="𬒗"')

,givenname,ngender_r,gender_w,gender_n,gender_nw,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,mean,median,mode,round
8015,𬒗,NaN,unknown,unknown,unknown,2.0,2.0,1.0,1.0,3.0,3.0,3.0,2.0,3.0,3.0,2.0,0.3125,0.25,0.25,2.0

In [8]:
x = (2.0+2.0+1.0+1.0+3.0+3.0+3.0+2.0+3.0+3.0+2.0)/11
x, (x - 1) / 4

(2.272727272727273, 0.31818181818181823)

In [9]:
tmp = df_gt.query("single_char == True and gender_w == 'unknown' and gender_nw=='female'")[['givenname','ngender_r','gender_w','gender_n','gender_nw','a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'a10', 'a11','mean','median','mode','round']]
tmp.reset_index(drop=True)

,givenname,ngender_r,gender_w,gender_n,gender_nw,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,mean,median,mode,round
0,仅,0.60040,unknown,female,female,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,0.458333,0.500,0.50,2.0
1,县,0.13905,unknown,female,female,3.0,3.0,1.0,2.0,3.0,3.0,3.0,2.0,3.0,1.0,3.0,0.354167,0.500,0.50,2.0
2,园,0.78480,unknown,female,female,4.0,4.0,3.0,4.0,3.0,4.0,3.0,4.0,3.0,3.0,5.0,0.625000,0.625,0.75,2.0
3,夜,0.60270,unknown,female,female,3.0,3.0,2.0,3.0,3.0,4.0,3.0,2.0,3.0,4.0,2.0,0.458333,0.500,0.50,2.0
4,杞,0.26155,unknown,female,female,2.0,1.0,3.0,5.0,2.0,4.0,4.0,3.0,3.0,3.0,3.0,0.479167,0.500,0.50,2.0
5,桓,0.11570,unknown,female,female,3.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,3.0,1.0,0.208333,0.250,0.25,2.0
6,洞,0.15180,unknown,female,female,3.0,2.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,1.0,2.0,0.291667,0.250,0.25,2.0
7,润,0.48830,unknown,female,female,4.0,3.0,2.0,2.0,3.0,4.0,3.0,2.0,3.0,3.0,3.0,0.458333,0.500,0.50,2.0
8,潭,0.18050,unknown,female,female,4.0,2.0,1.0,3.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,0.395833,0.500,0.50,2.0
9,琼,0.96450,unknown,female,female,4.0,4.0,5.0,4.0,4.0,5.0,4.0,5.0,5.0,4.0,5.0,0.812500,0.750,0.75,2.0
10,瑚,0.73470,unknown,female,female,4.0,4.0,5.0,4.0,3.0,4.0,4.0,4.0,5.0,5.0,5.0,0.770833,0.750,0.75,2.0
11,甄,0.73150,unknown,female,female,4.0,5.0,1.0,4.0,3.0,3.0,4.0,4.0,3.0,5.0,3.0,0.604167,0.625,0.75,2.0
12,硕,0.22380,unknown,female,female,3.0,2.0,1.0,2.0,3.0,2.0,3.0,1.0,2.0,3.0,3.0,0.312500,0.250,0.50,2.0
13,秘,0.61630,unknown,female,female,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,3.0,3.0,0.500000,0.500,0.50,2.0
14,秧,0.87620,unknown,female,female,4.0,2.0,3.0,2.0,3.0,4.0,3.0,4.0,3.0,3.0,3.0,0.500000,0.500,0.50,2.0
15,职,0.18910,unknown,female,female,3.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,0.395833,0.500,0.50,2.0
16,著,0.14540,unknown,female,female,3.0,2.0,2.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,0.416667,0.500,0.50,2.0
17,蔚,0.61130,unknown,female,female,4.0,4.0,2.0,4.0,4.0,4.0,2.0,5.0,3.0,3.0,4.0,0.604167,0.750,0.75,2.0
18,铉,0.14340,unknown,female,female,2.0,2.0,1.0,2.0,3.0,3.0,4.0,2.0,2.0,2.0,2.0,0.312500,0.250,0.25,2.0
19,闫,0.50245,unknown,female,female,3.0,2.0,1.0,1.0,3.0,2.0,3.0,1.0,4.0,4.0,2.0,0.333333,0.250,0.25,2.0

In [10]:
tmp['mean'].mean()

0.4645833333333333

In [11]:
tmp.query("givenname=='仅'")

,givenname,ngender_r,gender_w,gender_n,gender_nw,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,mean,median,mode,round
184,仅,0.6004,unknown,female,female,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,0.458333,0.5,0.5,2.0

In [12]:
x = (3.0+3.0+2.0+3.0+3.0+3.0+3.0+3.0+3.0+3.0+3.0)/11
x, (x - 1) / 4

(2.909090909090909, 0.4772727272727273)

In [13]:
tmp = df.query("gt == True and ~@pd.notna(ngender_r) and ~@pd.notna(mean_ngender_rn) and ~@pd.notna(mean_ngender_rnw)", engine='python')[['givenname','ngender_r','gender_w','gender_n','gender_nw','a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'a10', 'a11','mean','median','mode','round']]
tmp.reset_index(drop=True)

,givenname,ngender_r,gender_w,gender_n,gender_nw,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,mean,median,mode,round
0,𬒗,NaN,unknown,unknown,unknown,2.0,2.0,1.0,1.0,3.0,3.0,3.0,2.0,3.0,3.0,2.0,0.312500,0.250,0.25,2.0
1,𬕂,NaN,unknown,unknown,unknown,2.0,2.0,2.0,2.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,0.375000,0.375,0.25,2.0
2,𬘬,NaN,unknown,unknown,unknown,3.0,5.0,4.0,5.0,4.0,3.0,4.0,5.0,4.0,4.0,5.0,0.750000,0.750,0.75,2.0
3,𬘭,NaN,unknown,unknown,unknown,4.0,5.0,5.0,5.0,3.0,5.0,4.0,4.0,5.0,5.0,5.0,0.833333,1.000,1.00,2.0
4,𬬹,NaN,unknown,unknown,unknown,2.0,1.0,2.0,2.0,3.0,2.0,3.0,1.0,2.0,2.0,2.0,0.250000,0.250,0.25,2.0
5,𬬻,NaN,unknown,unknown,unknown,3.0,2.0,2.0,3.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,0.250000,0.250,0.25,2.0
6,𬭬,NaN,unknown,unknown,unknown,4.0,4.0,2.0,1.0,4.0,2.0,4.0,4.0,3.0,3.0,2.0,0.479167,0.500,0.75,2.0
7,𬯎,NaN,unknown,unknown,unknown,3.0,2.0,2.0,2.0,3.0,4.0,3.0,2.0,2.0,3.0,2.0,0.375000,0.250,0.25,2.0
8,𬳵,NaN,unknown,unknown,unknown,3.0,1.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,3.0,3.0,0.333333,0.250,0.25,2.0
9,𬺓,NaN,unknown,unknown,unknown,3.0,2.0,1.0,4.0,3.0,2.0,3.0,3.0,3.0,2.0,3.0,0.395833,0.500,0.50,2.0

In [14]:
tmp['mean'].mean()

0.4354166666666666

In [15]:
tmp.query("givenname=='𬒗'")

,givenname,ngender_r,gender_w,gender_n,gender_nw,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,mean,median,mode,round
8015,𬒗,NaN,unknown,unknown,unknown,2.0,2.0,1.0,1.0,3.0,3.0,3.0,2.0,3.0,3.0,2.0,0.3125,0.25,0.25,2.0

In [16]:
import numpy as np
x = np.median([2.0, 2.0, 1.0, 1.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 2.0])
x, (x - 1) / 4

(2.0, 0.25)

In [17]:
strategy = 251
cut = 4

In [18]:
tmp.loc[:,'label'] = tmp['median'].apply(lambda v: 'male' if v<0.3 else 'female' if v>0.7 else 'neutral')
tmp.drop(columns=['round']).sort_values('label')

,givenname,ngender_r,gender_w,gender_n,gender_nw,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,mean,median,mode,label
8022,𬘬,NaN,unknown,unknown,unknown,3.0,5.0,4.0,5.0,4.0,3.0,4.0,5.0,4.0,4.0,5.0,0.750000,0.750,0.75,female
8023,𬘭,NaN,unknown,unknown,unknown,4.0,5.0,5.0,5.0,3.0,5.0,4.0,4.0,5.0,5.0,5.0,0.833333,1.000,1.00,female
8015,𬒗,NaN,unknown,unknown,unknown,2.0,2.0,1.0,1.0,3.0,3.0,3.0,2.0,3.0,3.0,2.0,0.312500,0.250,0.25,male
8049,𬬹,NaN,unknown,unknown,unknown,2.0,1.0,2.0,2.0,3.0,2.0,3.0,1.0,2.0,2.0,2.0,0.250000,0.250,0.25,male
8050,𬬻,NaN,unknown,unknown,unknown,3.0,2.0,2.0,3.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,0.250000,0.250,0.25,male
8068,𬯎,NaN,unknown,unknown,unknown,3.0,2.0,2.0,2.0,3.0,4.0,3.0,2.0,2.0,3.0,2.0,0.375000,0.250,0.25,male
8071,𬳵,NaN,unknown,unknown,unknown,3.0,1.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,3.0,3.0,0.333333,0.250,0.25,male
8016,𬕂,NaN,unknown,unknown,unknown,2.0,2.0,2.0,2.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,0.375000,0.375,0.25,neutral
8059,𬭬,NaN,unknown,unknown,unknown,4.0,4.0,2.0,1.0,4.0,2.0,4.0,4.0,3.0,3.0,2.0,0.479167,0.500,0.75,neutral
8095,𬺓,NaN,unknown,unknown,unknown,3.0,2.0,1.0,4.0,3.0,2.0,3.0,3.0,3.0,2.0,3.0,0.395833,0.500,0.50,neutral