In [1]:
import pandas as pd
df_ch = pd.read_csv('class_mean_230_1_character_dictionary_withEng_name_gender.csv')
df_na = pd.read_csv('class_mean_230_1_CNKI_uniqueChineseGivenNames_gender.csv')

In [11]:
df_ch.query("character=='娟'")[['ngender_r','ngender_n','score','probabilityCalibrated','gender_n','gender_w']]

      ngender_r  ngender_n      score  probabilityCalibrated gender_n gender_w
2140    -0.9959   0.992656  12.301047               0.992656   female     male

In [17]:
df_na.query("givenname=='娟'")[['ngender_r','ngender_n','gender_n','gender_w']]

      ngender_r  ngender_n gender_n gender_w
1058    0.99795   0.706975   female     male