In [1]:
import pandas as pd
import glob
import os
import numpy as np

In [2]:
DATA_DIR = '../../results/CNKI'

In [3]:
def load_df(files):
    df = pd.DataFrame()
    for fn in files:
        tmp = pd.read_csv(fn, index_col=None)
        df = pd.concat([df, tmp])
    df.sort_values(['chunk_id','main_paper_id'], inplace=True)
    df.rename(columns={'main_paper_id':'chunk_paper_id'}, inplace=True)
    return df

In [4]:
df_publications = load_df(glob.glob(os.path.join(DATA_DIR,'chunk*publications.csv')))
df_references = load_df(glob.glob(os.path.join(DATA_DIR,'chunk*references.csv')))
df_citations = load_df(glob.glob(os.path.join(DATA_DIR,'chunk*citations.csv')))

In [5]:
df_publications.shape, df_references.shape, df_citations.shape
# ((84, 15), (915, 11), (2013, 11))

((84, 15), (915, 11), (2013, 11))

In [6]:
df_publications.loc[:, 'paper_id'] = np.arange(1,df_publications.shape[0]+1)
df_publications = df_publications[['paper_id', 'title', 'author', 'publication_date', 'source', 'database',
                                   'dbname', 'scode', 'sdb',
                                   'cites', 'downloads', 'result_rank', 'references_count', 'citations_count',
                                   'chunk_id', 'chunk_paper_id']]
df_publications.references_count = df_publications.references_count.astype(int)
df_publications.head(2)

,paper_id,title,author,publication_date,source,database,dbname,scode,sdb,cites,downloads,result_rank,references_count,citations_count,chunk_id,chunk_paper_id
0,1,亚皮秒光整流效应,马新发，张希成,1994-07-24,物理,期刊,CJFD9495,WLZZ407.001,CJFD,31,391,2,0,31,1,1
1,2,THz电磁场的新型电光探测技术及应用,"吕振国,吴起,张希成",1997-01-24,物理,期刊,CJFD9697,WLZZ701.013,CJFD,16,271,1,1,16,1,2

In [7]:
df_references = df_references.merge(df_publications[['chunk_id','chunk_paper_id','paper_id']], left_on=['chunk_id','chunk_paper_id'], right_on=['chunk_id','chunk_paper_id'], left_index=False, right_index=False).rename(columns={'order':'reference_id'})
df_references = df_references[['paper_id', 'reference_id', 'title', 'authors', 'journal', 'year', 'kind',
                               'filename', 'dbcode', 'dbname', 'chunk_id', 'chunk_paper_id']]
df_references.head(2)

,paper_id,reference_id,title,authors,journal,year,kind,filename,dbcode,dbname,chunk_id,chunk_paper_id
0,2,1,亚皮秒光整流效应,马新发，张希成,物理,1994(07),Journal,WLZZ407.001,CJFD,CJFD1994,1,2
1,3,1,Recent advances in terahertz imaging,"D.M. Mittleman,M. Gupta,R. Neelamani,R.G. Bara...",Applied Physics B Lasers and Optics,1999 (6),InternationalJournal,NaN,NaN,NaN,1,3

In [8]:
df_citations = df_citations.merge(df_publications[['chunk_id','chunk_paper_id','paper_id']], left_on=['chunk_id','chunk_paper_id'], right_on=['chunk_id','chunk_paper_id'], left_index=False, right_index=False).rename(columns={'order':'citation_id'})
df_citations = df_citations[['paper_id', 'citation_id', 'title', 'authors', 'journal', 'year', 'kind',
                             'filename', 'dbcode', 'dbname', 'chunk_id', 'chunk_paper_id']]
df_citations.head(2)

,paper_id,citation_id,title,authors,journal,year,kind,filename,dbcode,dbname,chunk_id,chunk_paper_id
0,1,1,基于纳米天线阵列非线性光学效应的太赫兹辐射特性研究,"靳延平,杨勇,徐新龙",光学学报,2022(15),Journal,GXXB202215002,DKFX,DKFXTEMP,1,1
1,1,2,Hg1-xCdxTe晶体生长及太赫兹性能研究,"王仍,林杏潮,张莉萍,张可锋,焦翠灵,陆液,邵秀华,李向阳,葛进,胡淑红,戴宁",红外与毫米波学报,2011(05),Journal,HWYH201105004,CJFD,CJFD2011,1,1

In [9]:
fn_pub = os.path.join(DATA_DIR, 'publications.csv')
# df_publications.set_index('paper_id').to_csv(fn_pub, index=True)
fn_pub

'../../results/CNKI/publications.csv'

In [10]:
fn_ref = os.path.join(DATA_DIR, 'references.csv')
# df_references.set_index(['paper_id','reference_id']).to_csv(fn_ref, index=True)
fn_ref

'../../results/CNKI/references.csv'

In [11]:
fn_cit = os.path.join(DATA_DIR, 'citations.csv')
# df_citations.set_index(['paper_id','citation_id']).to_csv(fn_cit, index=True)
fn_cit

'../../results/CNKI/citations.csv'