In [1]:
import sys
sys.path.append('../libs')

%load_ext autoreload
%autoreload 2

import ios
from tools_comparison import ToolsComparison

In [2]:
VERSION = 2
DATA = f'../../data/v{VERSION}/chinese_names'
RESULTS = f'../../results/v{VERSION}/chinese_gender'

DIR_TOOL_W = ios.path_join(RESULTS, 'tool_w')
DIR_TOOL_R = ios.path_join(RESULTS, 'tool_r')
DIR_TOOL_N = ios.path_join(RESULTS, 'tool_n')
DIR_GT = ios.path_join(DATA, 'annotations')

In [3]:
VERSION = 2
DIR = f'../../results/v{VERSION}/chinese_gender/comparison/<ML>/_<VAR_X>'
METRIC_CLASS = 'test_auc'
METRIC_REG = 'test_rmse'

# Best Model

## Classification

In [38]:
dir_class = DIR.replace('<ML>', 'classification')
df_class_mean = ios.load_json_files_to_dataframe(dir_class.replace('<VAR_X>', 'mean'))
df_class_median = ios.load_json_files_to_dataframe(dir_class.replace('<VAR_X>', 'median'))
df_class_mode = ios.load_json_files_to_dataframe(dir_class.replace('<VAR_X>', 'mode'))

df_class = ios.pd.concat([df_class_mean, df_class_median, df_class_mode], ignore_index=True)
cols = ['y','features_id','strategy_id','test_accuracy','test_f1','test_precision','test_recall','test_auc']
best_id_class = df_class[METRIC_CLASS].idxmax()

best_id_class, df_class.loc[best_id_class].features, df_class.loc[best_id_class].test_f1, df_class.loc[best_id_class].f_name

(102,
 ['ngender_r',
  'ngender_n',
  'gender_nw',
  'mean_ngender_rn',
  'mean_ngender_nw',
  'mean_ngender_rnw'],
 0.6507936507936508,
 'mean_230_1')

In [ ]:
# Best without W
filtered_df = df_class[df_class['features'].apply(lambda lst: all('w' not in item for item in lst))]
filtered_df.loc[filtered_df[METRIC_CLASS].idxmax()]

strategy_id                                                       1
features_id                                                       4
y                                                       gender_mean
features                                          [mean_ngender_rn]
nfeatures                                                         1
cat_features                                                     []
best_params       {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_re...
best_score        {'learn': {'MultiClass': 0.11031761220664968},...
best_iteration                                                   41
test_size                                                       0.2
random_state                                                  12345
loss_function                                            MultiClass
eval_metric                                              MultiClass
train_eval                                                 0.110318
test_accuracy                                                  0.95
test_f1                                                    0.649123
test_precision                                             0.633333
test_recall                                                0.666667
test_auc                                                   0.964912
all_accuracy                                                   0.91
all_f1                                                     0.615758
all_precision                                              0.608225
all_recall                                                 0.624217
all_auc                                                    0.969672
f_name                                                     mean_4_1
Name: 217, dtype: object

## Regression

In [41]:
dir_reg = DIR.replace('<ML>', 'regression')
df_reg_mean = ios.load_json_files_to_dataframe(dir_reg.replace('<VAR_X>', 'mean'))
df_reg_median = ios.load_json_files_to_dataframe(dir_reg.replace('<VAR_X>', 'median'))
df_reg_mode = ios.load_json_files_to_dataframe(dir_reg.replace('<VAR_X>', 'mode'))

df_reg = ios.pd.concat([df_reg_mean, df_reg_median, df_reg_mode], ignore_index=True)
cols = ['y','features_id','strategy_id','test_accuracy','test_f1','test_precision','test_recall','test_auc']
best_id_reg = df_reg[METRIC_REG].idxmin()

best_id_reg, df_reg.loc[best_id_reg].features, df_reg.loc[best_id_reg].test_rmse, df_reg.loc[best_id_reg].f_name

(13,
 "['ngender_r', 'gender_nw', 'mean_ngender_rnw']",
 0.11064767112482991,
 'mean_50')

In [ ]:
# Best without W
filtered_df = df_reg[df_reg['features'].apply(lambda lst: all('w' not in item for item in lst))]
filtered_df.loc[filtered_df[METRIC_REG].idxmin()]

y                                                              mean
features_id                                                       0
features                                              ['ngender_r']
nfeatures                                                         1
cat_features                                                     []
best_params       {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_re...
best_score        {'learn': {'RMSE': 0.11167467481312734}, 'vali...
best_iteration                                                   80
test_size                                                       0.2
random_state                                                  12345
loss_function                                                  RMSE
eval_metric                                                    RMSE
train_eval                                                 0.111675
test_r2                                                    0.823782
test_rmse                                                  0.128159
all_r2                                                     0.842802
all_rmse                                                   0.118363
f_name                                                       mean_0
Name: 130, dtype: object

# Data

## Given Names

In [12]:
tc = ToolsComparison(dir_tool_w=DIR_TOOL_W, dir_tool_r=DIR_TOOL_R, dir_tool_n=DIR_TOOL_N, dir_gt=DIR_GT)
tc.load_data()
tc.compare_unique_chinese_given_names()
tc.df_ch_genders.head(2)

,ngender_r,gender_w,0,1,2,3,4,5,6,7,...,std_ngender_rnw,std_ngender_rn,std_ngender_rw,std_ngender_nw,mode,mode_ngender_rnw,mode_ngender_rn,mode_ngender_rw,mode_ngender_nw,gender_nw
givenname,,,,,,,,,,,,,,,,,,,,,
俊池,0.30315,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.161985,0.035063,0.151575,0.186638,NaN,0.30315,0.30315,0.30315,0.373277,male
建军,0.14830,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.125561,0.079598,0.074150,0.153748,NaN,0.14830,0.14830,0.14830,0.307495,male

In [14]:
tc.df_ch_genders.shape

(39713, 40)

## Dictionary Chinese Characters

In [15]:
FN_DICT_NAMSOR = f'../../results/v{VERSION}/chinese_gender/tool_n/character_dictionary_withEng_name_gender.csv'
df_dict_gender = ios.load_csv(FN_DICT_NAMSOR)
df_dict_gender.head(2)

,character,pinyin_hanziDB,pinyin_qxk,meaning,pinyin_hanziDB_qxk,pinyin_name,pinyin_givenname,pinyin_familyname,pinyin,tone,...,NC,apiVersion,script,id,firstName,lastName,likelyGender,genderScale,score,probabilityCalibrated
0,一,yī,yī,yī\t1:数目字，最小的正整数。2:相同。～样|～起|～致|统～|说法不～。3:全；满。～...,yī,yī,yī,yī,yī,1,...,3.0,namsor_api_2.1.1,HAN,3f22e65c-c4e7-4888-a6ca-79194d6a4dbe,一,NaN,male,-0.453237,3.152061,0.726618
1,乙,yǐ,yǐ,yǐ\t1:天干的第二位，常用作顺序的第二。2:中国民族音乐音阶的一级，乐谱上用作记音符号，...,yǐ,yǐ,yǐ,yǐ,yǐ,3,...,2.8,namsor_api_2.1.1,HAN,760f4156-6964-471c-961f-399162d20874,乙,NaN,female,0.972487,10.789135,0.986244

In [16]:
df_dict_gender.shape

(8096, 35)

# Prediction

In [21]:
# predict gender using best classification model
fn_class_model = df_class.loc[best_id_class].f_name
path = DIR.replace('<ML>', 'classification')
path = path.replace('<VAR_X>', fn_class_model.split("_")[0])
fn_class_model = ios.path_join(path, f"{fn_class_model}.cbm")
fn_class_model

'../../results/v2/chinese_gender/comparison/classification/_mean/mean_230_1.cbm'

In [22]:
# predict gender using best regression model
fn_reg_model = df_reg.loc[best_id_reg].f_name
path = DIR.replace('<ML>', 'regression')
path = path.replace('<VAR_X>', fn_reg_model.split("_")[0])
fn_reg_model = ios.path_join(path, f"{fn_reg_model}.cbm")
fn_reg_model

'../../results/v2/chinese_gender/comparison/regression/_mean/mean_50.cbm'

In [42]:
from catboost import CatBoostRegressor
model = CatBoostRegressor()
model.load_model('../../results/v2/chinese_gender/comparison/regression/_mean/mean_50.cbm', format="cbm")
model

['ngender_r', 'gender_nw', 'mean_ngender_rnw']