In [1]:
import pandas as pd
import glob
import os
import numpy as np

In [2]:
DATA_DIR = '../../results/'

In [3]:
def load_df(files):
    df = pd.DataFrame()
    for fn in files:
        tmp = pd.read_csv(fn, index_col=None)
        df = pd.concat([df, tmp])
    df.sort_values(['chunk_id','main_paper_id'], inplace=True)
    df.rename(columns={'main_paper_id':'chunk_paper_id'}, inplace=True)
    return df

In [4]:
df_publications = load_df(glob.glob(os.path.join(DATA_DIR,'chunk*publications.csv')))
df_references = load_df(glob.glob(os.path.join(DATA_DIR,'chunk*references.csv')))
df_citations = load_df(glob.glob(os.path.join(DATA_DIR,'chunk*citations.csv')))

In [5]:
df_publications.shape, df_references.shape, df_citations.shape

((84, 15), (915, 11), (2013, 11))

In [6]:
df_publications.loc[:, 'paper_id'] = np.arange(1,df_publications.shape[0]+1)
df_publications = df_publications[['paper_id', 'title', 'author', 'publication_date', 'source', 'database',
                                   'dbname', 'scode', 'sdb',
                                   'cites', 'downloads', 'result_rank', 'references_count', 'citations_count',
                                   'chunk_id', 'chunk_paper_id']]
df_publications.references_count = df_publications.references_count.astype(int)
df_publications

,paper_id,title,author,publication_date,source,database,dbname,scode,sdb,cites,downloads,result_rank,references_count,citations_count,chunk_id,chunk_paper_id
0,1,亚皮秒光整流效应,马新发，张希成,1994-07-24,物理,期刊,CJFD9495,WLZZ407.001,CJFD,31,391,2,0,31,1,1
1,2,THz电磁场的新型电光探测技术及应用,"吕振国,吴起,张希成",1997-01-24,物理,期刊,CJFD9697,WLZZ701.013,CJFD,16,271,1,1,16,1,2
2,3,THz技术的应用及展望,"王少宏,许景周,汪力,张希成",2001-10-24,物理,期刊,CJFD2001,WLZZ200110006,CJFD,280,1395,18,13,292,1,3
3,4,太赫兹科学与技术研究回顾,"Bradley Ferguson,张希成",2003-05-24,物理,期刊,CJFD2003,WLZZ200305002,CJFD,399,4091,2,54,453,1,4
4,5,使用太赫兹技术研究航天飞机失事的原因,"谢旭,钟华,袁韬,许景周,张希成",2003-09-24,物理,期刊,CJFD2003,WLZZ200309006,CJFD,96,629,1,0,96,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,80,电流变液中电场强度的半解析计算,"李向亭,马红孺",2000-06-12,物理学报,期刊,CJFD2000,WLXB200006010,CJFD,5,90,1,2,6,10,5
5,81,电磁超散射和隐形门,陈焕阳;段琦琳;伍瑞新;马红孺;,2022-12-12,物理,期刊,CJFDLAST2023,WLZZ202212006,CJFD,1,134,1,37,2,10,6
6,82,磁性金属超晶格中的自旋波,"马红孺,蔡建华",1984-03-31,物理学报,期刊,CJFD7984,WLXB198403022,CJFD,2,50,1,1,2,10,7
7,83,约束条件下的硬球流体,"诸蔚朝,李卫华,马红孺",2002-08-27,化学物理学报,期刊,CJFD2002,HXWL200204008,CJFD,8,93,1,20,28,10,8
8,84,软凝聚态物质物理学,"马红孺,陆坤权",2000-09-24,物理,期刊,CJFD2000,WLZZ200009001,CJFD,47,1178,6,6,52,10,9

In [7]:
df_references = df_references.merge(df_publications[['chunk_id','chunk_paper_id','paper_id']], left_on=['chunk_id','chunk_paper_id'], right_on=['chunk_id','chunk_paper_id'], left_index=False, right_index=False).rename(columns={'order':'reference_id'})
df_references = df_references[['paper_id', 'reference_id', 'title', 'authors', 'journal', 'year', 'kind',
                               'filename', 'dbcode', 'dbname', 'chunk_id', 'chunk_paper_id']]
df_references

,paper_id,reference_id,title,authors,journal,year,kind,filename,dbcode,dbname,chunk_id,chunk_paper_id
0,2,1,亚皮秒光整流效应,马新发，张希成,物理,1994(07),Journal,WLZZ407.001,CJFD,CJFD1994,1,2
1,3,1,Recent advances in terahertz imaging,"D.M. Mittleman,M. Gupta,R. Neelamani,R.G. Bara...",Applied Physics B Lasers and Optics,1999 (6),InternationalJournal,NaN,NaN,NaN,1,3
2,3,2,NaN,"Corson J, Mallozzi R, Orenstein J et al",Nature,1999,OtherLang,NaN,NaN,NaN,1,3
3,3,3,NaN,"Cheville RA, Grischkowsky D, Opt",Lett,1995,OtherLang,NaN,NaN,NaN,1,3
4,3,4,NaN,"Grischkowsky D, Soren Keiding, Martin van Exte...",Journal of the Optical Society of America B Op...,1990,OtherLang,NaN,NaN,NaN,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...
910,84,2,NaN,Lubensky T C,Solid State Communications,1997,OtherLang,NaN,NaN,NaN,10,9
911,84,3,NaN,固、特、异的软物质,"郭兆林,周念萦译.",1999,OtherLang,NaN,NaN,NaN,10,9
912,84,4,NaN,Soft Matter Physics,"DAOUD M, WILLIAMS C E. Springer",1999,OtherLang,NaN,NaN,NaN,10,9
913,84,5,NaN,"de,Gennes,P","G.,Prost,J. The Physics of Liquid Crystals",1993,OtherLang,NaN,NaN,NaN,10,9
914,84,6,NaN,Structural Ordering in Colloidal Suspensions,"Sood Ajay K. In:Solid State Physics, Volume 45...",1991,OtherLang,NaN,NaN,NaN,10,9

In [8]:
df_citations = df_citations.merge(df_publications[['chunk_id','chunk_paper_id','paper_id']], left_on=['chunk_id','chunk_paper_id'], right_on=['chunk_id','chunk_paper_id'], left_index=False, right_index=False).rename(columns={'order':'citation_id'})
df_citations = df_citations[['paper_id', 'citation_id', 'title', 'authors', 'journal', 'year', 'kind',
                             'filename', 'dbcode', 'dbname', 'chunk_id', 'chunk_paper_id']]
df_citations

,paper_id,citation_id,title,authors,journal,year,kind,filename,dbcode,dbname,chunk_id,chunk_paper_id
0,1,1,基于纳米天线阵列非线性光学效应的太赫兹辐射特性研究,"靳延平,杨勇,徐新龙",光学学报,2022(15),Journal,GXXB202215002,DKFX,DKFXTEMP,1,1
1,1,2,Hg1-xCdxTe晶体生长及太赫兹性能研究,"王仍,林杏潮,张莉萍,张可锋,焦翠灵,陆液,邵秀华,李向阳,葛进,胡淑红,戴宁",红外与毫米波学报,2011(05),Journal,HWYH201105004,CJFD,CJFD2011,1,1
2,1,3,光整流太赫兹源及其研究进展,"邵立,路纲,程东明",激光与红外,2008(09),Journal,JGHW200809002,CJFD,CJFD2008,1,1
3,1,4,光学整流产生和电光取样探测THz辐射的数值模拟,贾红宝,辽宁科技大学学报,2008(Z1),Journal,ASGT2008Z1005,CJFD,CJFD2008,1,1
4,1,5,THz电磁场的新型电光探测技术及应用,"吕振国,吴起,张希成",物理,1997(01),Journal,WLZZ701.013,CJFD,CJFD1997,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2008,84,48,带电胶体系统中有效作用的研究,胡苹,湖南师范大学,2006,Dissertation,2006076177.nh,CMFD,CMFD2006,10,9
2009,84,49,几何约束下胶体排空作用的模拟研究,郭纪源,湖南师范大学,2005,Dissertation,2005113424.nh,CMFD,CMFD2005,10,9
2010,84,50,固体“类流态”现象的混沌动力学特征及机理研究,张贵杰,天津大学,2004,Thesis,2006011521.nh,CDFD,CDFD2006,10,9
2011,84,51,无机纳米微粒体系的共振瑞利散射光谱研究及分析新应用,蒋治良,西南师范大学,2003,Thesis,2003090018.nh,CDFD,CDFD2003,10,9
2012,84,52,两亲嵌段共聚物：分子设计及溶液中自组装形态控制,袁建军,浙江大学,2002,Thesis,2003062419.nh,CDFD,CDFD2002,10,9

In [9]:
fn_pub = os.path.join(DATA_DIR, 'publications.csv')
df_publications.set_index('paper_id').to_csv(fn_pub, index=True)
fn_pub

'../../results/publications.csv'

In [10]:
fn_ref = os.path.join(DATA_DIR, 'references.csv')
df_references.set_index(['paper_id','reference_id']).to_csv(fn_ref, index=True)
fn_ref

'../../results/references.csv'

In [11]:
fn_cit = os.path.join(DATA_DIR, 'citations.csv')
df_citations.set_index(['paper_id','citation_id']).to_csv(fn_cit, index=True)
fn_cit

'../../results/citations.csv'